exclude: ^(data/)
repos:

# TODO: Need to set up with pycharm
#- repo: https://github.com/pre-commit/mirrors-isort
#  rev: v4.3.17
#  hooks:
#  - id: isort

- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.7

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
    - id: flake8
      language_version: python3.7

#- repo: https://github.com/pre-commit/mirrors-mypy
#  rev: v0.701
#  hooks:
#    - id: mypy
#      language_version: python3.7
